# Generated by Django 5.2.4 on 2025-10-08 18:16

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.CharField(default=core.models.generate_custom_question_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.CharField(default=core.models.generate_custom_schedule_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('exam_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_start_time', models.CharField(blank=True, max_length=8, null=True)),
                ('exam_end_time', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_earning', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'salary_component',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=core.models.generate_custom_user_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=core.models.generate_custom_user_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this admin belongs to.', related_name='admin_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='admin_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'admin',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_main_company', models.BooleanField(default=False)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_companies', to='core.company')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='Current', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'company_bank_account',
            },
        ),
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('AUTOMATED', 'Automated')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_backup',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sub-Manager', 'Sub-Manager'), ('HR', 'HR'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], max_length=20)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('client_code', models.CharField(blank=True, max_length=30, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='active', help_text='Approval status for new accounts', max_length=20)),
                ('approval_workflow_id', models.IntegerField(blank=True, help_text='Associated approval workflow ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Employee who approved this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', to='core.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='Employee who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to='core.employee')),
                ('main_company', models.ForeignKey(blank=True, limit_choices_to={'is_main_company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_employees', to='core.company')),
                ('sub_company', models.ForeignKey(blank=True, limit_choices_to={'is_main_company': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_employees', to='core.company')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('APPOINTMENT', 'Appointment Order'), ('ESI_CARD', 'ESI Card'), ('ID_CARD', 'ID Card'), ('RELIEVING', 'Relieving Letter')], max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('issued_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=35)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'BankDetails',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('employee', 'Employee Creation'), ('hr', 'HR Account Creation'), ('supervisor', 'Supervisor Account Creation'), ('sub_manager', 'Sub-Manager Account Creation'), ('manager', 'Manager Account Creation'), ('sub_company', 'Sub-Company Creation')], default='employee', help_text='Type of approval request', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the workflow', max_length=30)),
                ('current_stage', models.CharField(choices=[('sub_manager', 'Awaiting Sub-Company Manager'), ('main_manager', 'Awaiting Main Company Manager'), ('admin', 'Awaiting Admin'), ('completed', 'Completed')], default='sub_manager', help_text='Current approval stage in the workflow', max_length=30)),
                ('request_data', models.JSONField(default=dict, help_text='Data for the creation request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection if applicable', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or comments', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when workflow was completed', null=True)),
                ('company', models.ForeignKey(help_text='Company where this request originated', on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='core.company')),
                ('sub_company', models.ForeignKey(blank=True, help_text='Sub-company if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_approvals', to='core.company')),
                ('created_by', models.ForeignKey(help_text='Employee who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_workflows', to='core.employee')),
            ],
            options={
                'db_table': 'approval_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Next Level')], default='pending_approval', max_length=30)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.approvalworkflow')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_notifications', to='core.employee')),
            ],
            options={
                'db_table': 'approval_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Workflow Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=30)),
                ('stage', models.CharField(max_length=30)),
                ('actor_role', models.CharField(help_text='Role at time of action', max_length=50)),
                ('comments', models.TextField(blank=True, default='', help_text='Comments from the approver', null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of this action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Browser/client user agent string', max_length=500, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.approvalworkflow')),
                ('actor', models.ForeignKey(help_text='Employee who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to='core.employee')),
            ],
            options={
                'verbose_name_plural': 'Approval Histories',
                'db_table': 'approval_history',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('PROBATION', 'Probation')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_period_months', models.PositiveIntegerField(default=6)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'employee_contract',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDisciplinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WARNING', 'Warning'), ('SHOW_CAUSE', 'Show Cause Notice'), ('SUSPENSION', 'Suspension'), ('TERMINATION', 'Termination'), ('FINE', 'Fine')], max_length=20)),
                ('reason', models.TextField()),
                ('action_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='disciplinary_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'employee_disciplinary',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('COMP_OFF', 'Compensatory Off')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'employee_leave',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('esi_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_uan_number', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=15, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'IdentityDocument',
            },
        ),
        migrations.CreateModel(
            name='IncrementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'IncrementHistory',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', 'Appointment Order Issued'), ('PAYSLIP', 'Payslip Uploaded'), ('SALARY', 'Salary Credited'), ('DOCUMENT', 'Document Uploaded'), ('LEAVE', 'Leave Status Update'), ('ATTENDANCE', 'Attendance Update'), ('GENERAL', 'General Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('recipient', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'notification_queue',
            },
        ),
        migrations.CreateModel(
            name='OfficialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], max_length=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'OfficialDetails',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'OvertimeRecord',
            },
        ),
        migrations.CreateModel(
            name='PayrollLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_payrolls', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_lock',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_file', models.FileField(upload_to='payslips/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'Payslip',
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Temporary username for the pending user', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Email address for the pending user', max_length=254, unique=True)),
                ('temporary_password', models.CharField(help_text='Hashed password (stored securely)', max_length=255)),
                ('employee_data', models.JSONField(default=dict, help_text='Employee details in JSON format')),
                ('official_details_data', models.JSONField(blank=True, default=dict, help_text='Official/organizational details if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Approval request expires after 30 days', null=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to='core.approvalworkflow')),
            ],
            options={
                'db_table': 'pending_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('current_value', models.TextField()),
                ('requested_value', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='core.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_update_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_amount_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'reimbursement_category',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('bill_date', models.DateField()),
                ('receipt', models.FileField(upload_to='reimbursement_receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reimbursementcategory')),
            ],
            options={
                'db_table': 'employee_reimbursement',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SALARY_STATEMENT', 'Salary Statement'), ('DEDUCTION_STATEMENT', 'Deduction Statement'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate')], max_length=30)),
                ('file', models.FileField(upload_to='employee_reports/')),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('ATTENDANCE', 'Attendance Report'), ('SALARY', 'Salary Report'), ('ESI', 'ESI Report'), ('PF', 'PF Report'), ('PT', 'PT Report'), ('LWF', 'LWF Report')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('recipients', models.TextField()),
                ('next_run_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedule',
            },
        ),
        migrations.CreateModel(
            name='ClientProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esi_applicable', models.BooleanField(default=False)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('pt_applicable', models.BooleanField(default=False)),
                ('lwf_applicable', models.BooleanField(default=False)),
                ('advance_applicable', models.BooleanField(default=False)),
                ('insurance_applicable', models.BooleanField(default=False)),
                ('service_charge_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=10)),
                ('service_charge_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.OneToOneField(limit_choices_to={'is_main_company': False}, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('esi_components', models.ManyToManyField(blank=True, related_name='esi_components', to='core.salarycomponent')),
                ('pf_components', models.ManyToManyField(blank=True, related_name='pf_components', to='core.salarycomponent')),
                ('pt_components', models.ManyToManyField(blank=True, related_name='pt_components', to='core.salarycomponent')),
            ],
            options={
                'db_table': 'client_profile_settings',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pt_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lwf_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'SalaryStructure',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration_minutes', models.PositiveIntegerField(default=60)),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=480)),
                ('night_shift_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift')),
            ],
            options={
                'db_table': 'employee_shift',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_configuration',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('employee_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('last_client_switch', models.DateTimeField(blank=True, null=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('assigned_companies', models.ManyToManyField(blank=True, to='core.company')),
                ('current_client', models.ForeignKey(blank=True, limit_choices_to={'is_main_company': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock')], max_length=20)),
                ('description', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_b4ff78_idx'), models.Index(fields=['action', 'timestamp'], name='activity_lo_action_53e6ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('APPOINTMENT_ORDER', 'Appointment Order'), ('PAYSLIP', 'Payslip'), ('RELIEVING_LETTER', 'Relieving Letter'), ('ESI_CARD', 'ESI Card'), ('LEAVE_APPROVAL', 'Leave Approval'), ('LEAVE_REJECTION', 'Leave Rejection')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'email_template',
                'unique_together': {('template_type', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('WO', 'Weekly Off'), ('H', 'Holiday'), ('HD', 'Half Day')], max_length=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status', 'current_stage'], name='approval_wo_status_d35de1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approval_type', 'status'], name='approval_wo_approva_f3bcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['company', 'status'], name='approval_wo_company_1b1446_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('company', 'date')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['employee', 'is_read', 'created_at'], name='notificatio_employe_dceb9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrolllock',
            unique_together={('company', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
