# Generated by Django 5.2.4 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='approval_status',
            field=models.CharField(default='active', help_text='Approval status for new accounts', max_length=20),
        ),
    ]
