# Generated by Django 5.2.4 on 2025-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_check_in_time_attendance_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervised_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies supervised by this supervisor', related_name='supervisors', to='core.company'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='approval_type',
            field=models.CharField(choices=[('employee', 'Employee Creation'), ('hr', 'HR Account Creation'), ('supervisor', 'Supervisor Account Creation'), ('sub_manager', 'Sub-Manager Account Creation'), ('manager', 'Manager Account Creation'), ('sub_company', 'Sub-Company Creation')], default='employee', help_text='Type of approval request', max_length=30),
        ),
    ]
