# Generated by Django 5.2.4 on 2025-10-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_supervised_companies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_1_status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('WO', 'Weekly Off'), ('H', 'Holiday'), ('HD', 'Half Day')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_2_status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('WO', 'Weekly Off'), ('H', 'Holiday'), ('HD', 'Half Day')], default='A', max_length=2),
        ),
    ]
